### PR TITLE
Added Gallery Functionality

### PR DESCRIPTION
**Pull request by Naatchi**
I added new files under the directory of gallery and one file titled gallery.html

### CODE REVIEW

**Comment by 0ffz** [comment]
CSS and js look alright, I'll checkout locally later and leave some feedback from there 👍

**Comment by 0ffz** [comment]
Quick comment before i start a proper review, I think the way you made images use three columns makes the images tiny on mobile.

image

Also the buttons for going to gallery and suggesting things aren't centered, plz do that ;p

Now that we have auto PR publishing it'll be a lot easier to check out what uve made!

**Comment by 0ffz** [comment]
Only small thing I'd want to ask about is making it so when you click the gray background outside the image preview, it gets closed. Would that be easy enough to do?

**Comment by Naatchi** [comment]
> Only small thing I'd want to ask about is making it so when you click the gray background outside the image preview, it gets closed. Would that be easy enough to do?

yeah i can go ahead and do that

**Comment by Naatchi** [comment]
I'll also go ahead and make that close change to the desktop version also

**Comment by 0ffz** [comment]
I sadly think the loading times as it stands right now make the gallery barely usable. I don't think it's possible to easily make rescaled versions of the things so we've two options: make images fit the full screen and blow em all. the. way. up. Like 1 column only kinda deal... and let lazyloading offset that load time.

or find some library that can somehow support this on static files, which I don't think is possible, but maybe you know more than me about this?

**Comment by Naatchi** [comment]
bro this has been open for over a year 😭

**Pull request closed without merging**
